name: Build and Deploy Docs

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust based on your project requirements
          tools: composer

      - name: Install dependencies
        run: |
            composer install --prefer-dist

      - name: Generate Documentation
        run: |
            vendor/bin/phpdoc -c phpdoc.xml
            
      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GH_TOKEN }}
      #    publish_dir: ./docs/build
      #    publish_branch: gh-pages
      
      - name: Create archives
        run: |
            7z a -r standalone.zip .
            7z a -r core.zip . -x!vendor/*

      #- name: Upload archives
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: phpstan-json-report
      #  path: |
      #      standalone.zip
      #      core.zip
                     
      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release"
          files: |
            standalone.zip
            core.zip