name: Build and Deploy Docs

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust based on your project requirements
          tools: composer

      - name: Install dependencies
        run: |
            composer install --prefer-dist

      - name: Generate Documentation
        run: |
            vendor/bin/phpdoc -c phpdoc.xml

  create-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/cicd'
    needs: [docs]
    runs-on: ubuntu-latest
    steps:         
      - name: Create archives
        run: |
            7z a -r standalone.zip . -x!.git -x!.github -x!.phpdoc
            7z a -r core.zip . -x!vendor -x!.git -x!.github -x!.phpdoc -x!*.zip
          
      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release"
          files: |
            standalone.zip
            core.zip